// styles/chatStyles.ts
import { StyleSheet } from 'react-native';

export const chatStyles = StyleSheet.create({
  // Container styles
  safeArea: {
    flex: 1,
    backgroundColor: '#F0F9FF',
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: '#F0F9FF',
  },

  // Header styles - Colorful gradient
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 8,
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    borderRadius: 20,
    marginHorizontal: 8,
    marginTop: 8,
    marginBottom: 8,
    shadowColor: '#667eea',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 8,
  },
  menuButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.2)',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  menuText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0F131A',
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0F131A',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(255,255,255,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  clearButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  clearButtonText: {
    color: '#0F131A',
    fontWeight: '700',
    fontSize: 14,
  },

  // ScrollView styles
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },

  // Message container styles
  messageContainer: {
    marginBottom: 20,
  },
  userMessageContainer: {
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  aiMessageContainer: {
    alignItems: 'flex-start',
    marginBottom: 12,
  },

  // Bubble styles - Colorful gradients
  userBubble: {
    backgroundColor: 'linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)',
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 20,
    borderBottomRightRadius: 6,
    maxWidth: '80%',
    shadowColor: '#3B82F6',
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 6,
  },
  aiBubble: {
    maxWidth: '90%',
    width: '100%',
  },
  userText: {
    color: '#0F131A',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: 22,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },

  // Base card style - Colorful variants
  card: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 20,
    marginTop: 16,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 16,
    elevation: 6,
    borderWidth: 2,
    borderColor: 'transparent',
  },

  // Response card for simple messages
  responseCard: {
    backgroundColor: '#FFFFFF',
    borderLeftWidth: 6,
    borderLeftColor: '#3B82F6',
    borderColor: '#EFF6FF',
  },
  responseText: {
    fontSize: 16,
    color: '#374151',
    lineHeight: 24,
    fontWeight: '500',
  },

  // Specialized card variants - Colorful
  welcomeCard: {
    alignItems: 'center',
    paddingVertical: 32,
    backgroundColor: 'linear-gradient(135deg, #A5B4FC 0%, #C4B5FD 100%)',
    borderColor: '#C4B5FD',
  },
  welcomeTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#0F131A',
    marginBottom: 12,
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  welcomeText: {
    fontSize: 16,
    color: '#0F131A',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '500',
  },

  loadingCard: {
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    paddingVertical: 24,
  },
  loadingText: {
    marginTop: 12,
    color: '#64748B',
    fontSize: 14,
    fontWeight: '600',
  },

  // Diagnosis card styles - Purple theme
  diagnosisCard: {
    borderLeftWidth: 6,
    borderLeftColor: '#8B5CF6',
    backgroundColor: '#FAF5FF',
    borderColor: '#EDE9FE',
  },
  diagnosisTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#6D28D9',
    marginBottom: 16,
  },
  diagnosisList: {
    marginBottom: 16,
  },
  diagnosisItem: {
    marginBottom: 8,
    paddingLeft: 8,
  },
  diagnosisText: {
    fontSize: 16,
    color: '#5B21B6',
    fontWeight: '600',
    lineHeight: 22,
  },

  // Reasoning styles - Blue theme
  reasoningContainer: {
    backgroundColor: 'linear-gradient(135deg, #E0F2FE 0%, #BAE6FD 100%)',
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#0EA5E9',
    marginTop: 12,
  },
  reasoningTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0369A1',
    marginBottom: 8,
  },
  reasoningText: {
    fontSize: 15,
    color: '#0C4A6E',
    lineHeight: 22,
    fontWeight: '500',
  },

  // Symptom analysis styles - Green theme
  symptomCard: {
    borderLeftWidth: 6,
    borderLeftColor: '#10B981',
    backgroundColor: '#F0FDF4',
    borderColor: '#DCFCE7',
  },
  symptomTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#047857',
    marginBottom: 20,
  },
  severityMeter: {
    marginBottom: 20,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  severityLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  severityLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  severityBar: {
    height: 12,
    backgroundColor: '#E5E7EB',
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 8,
  },
  severityFill: {
    height: '100%',
    borderRadius: 6,
  },
  severityValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#065F46',
    textAlign: 'center',
  },
  symptomItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1FAE5',
  },
  symptomName: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '600',
    width: '40%',
  },
  symptomIntensity: {
    flex: 1,
    height: 8,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
    overflow: 'hidden',
    marginHorizontal: 12,
  },
  symptomIntensityBar: {
    height: '100%',
    backgroundColor: 'linear-gradient(90deg, #10B981 0%, #059669 100%)',
    borderRadius: 4,
  },
  symptomIntensityText: {
    fontSize: 12,
    color: '#065F46',
    fontWeight: '700',
    width: '15%',
    textAlign: 'right',
  },

  // Advice card styles - Orange theme
  adviceCard: {
    borderLeftWidth: 6,
    borderLeftColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
    borderColor: '#FEF3C7',
  },
  adviceTitle: {
    fontWeight: '800',
    color: '#92400E',
    marginBottom: 16,
    fontSize: 20,
    letterSpacing: -0.3,
  },
  adviceItem: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#FEF3C7',
  },
  adviceStepHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  adviceStepNumber: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
    backgroundColor: '#F59E0B',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 12,
    minWidth: 24,
    textAlign: 'center',
  },
  adviceStep: {
    color: '#92400E',
    fontWeight: '700',
    fontSize: 16,
    flex: 1,
  },
  adviceDetails: {
    color: '#B45309',
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '500',
  },

  // Warning/Care styles - Yellow theme
  warningCard: {
    backgroundColor: '#FFFBEB',
    borderColor: '#FEF3C7',
    borderLeftWidth: 6,
    borderLeftColor: '#F59E0B',
  },
  warningTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#92400E',
    marginBottom: 12,
  },
  careItem: {
    marginBottom: 10,
    paddingLeft: 8,
  },
  careText: {
    fontSize: 15,
    color: '#B45309',
    lineHeight: 22,
    fontWeight: '600',
  },

  // Emergency styles - Red theme
  emergencyCard: {
    borderLeftWidth: 6,
    borderLeftColor: '#EF4444',
    backgroundColor: 'linear-gradient(135deg, #FEE2E2 0%, #FECACA 100%)',
    borderColor: '#FECACA',
  },
  emergencyTitle: {
    color: '#991B1B',
    fontWeight: '800',
    marginBottom: 12,
    fontSize: 20,
  },
  emergencyText: {
    color: '#7F1D1D',
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '600',
  },

  // Error styles - Red theme
  errorCard: {
    borderLeftWidth: 6,
    borderLeftColor: '#EF4444',
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  errorTitle: {
    color: '#991B1B',
    fontWeight: '700',
    marginBottom: 8,
    fontSize: 18,
  },
  errorText: {
    color: '#7F1D1D',
    fontSize: 15,
    lineHeight: 22,
  },

  // Disclaimer card - Yellow theme
  disclaimerCard: {
    backgroundColor: '#FFFBEB',
    borderLeftColor: '#EAB308',
    borderLeftWidth: 6,
  },
  disclaimerText: {
    fontSize: 13,
    color: '#92400E',
    fontStyle: 'italic',
    lineHeight: 18,
    textAlign: 'center',
    fontWeight: '500',
  },

  // Input bar styles - Colorful
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    padding: 8,
    marginBottom: 20,
    marginTop: 12,
    marginHorizontal: 8,
    shadowColor: '#3B82F6',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#E0F2FE',
  },
  input: {
    flex: 1,
    height: 48,
    paddingHorizontal: 18,
    color: '#0F131A',
    fontSize: 16,
    fontWeight: '500',
    borderRadius: 20,
  },
  inputWarning: {
    borderColor: '#F59E0B',
    backgroundColor: '#FFFBEB',
  },
  sendBtn: {
    backgroundColor: 'linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%)',
    paddingHorizontal: 24,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    shadowColor: '#3B82F6',
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 6,
  },
  sendBtnWarning: {
    backgroundColor: 'linear-gradient(135deg, #F59E0B 0%, #D97706 100%)',
  },
  sendBtnDisabled: {
    opacity: 0.6,
    shadowOpacity: 0.1,
  },
  sendBtnText: {
    color: '#0F131A',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: -0.2,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 1,
  },

  // Analysis Offer Modal Styles - Colorful
  analysisOfferContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  analysisOfferCard: {
    backgroundColor: 'linear-gradient(135deg, #A5B4FC 0%, #C4B5FD 100%)',
    borderRadius: 24,
    padding: 28,
    margin: 20,
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  analysisOfferTitle: {
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 16,
    textAlign: 'center',
    color: '#0F131A',
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  analysisOfferText: {
    fontSize: 16,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
    fontWeight: '500',
  },
  analysisOfferButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  analysisOfferButton: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 16,
    flex: 1,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  analysisOfferButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 16,
    flex: 1,
    alignItems: 'center',
  },
  analysisOfferButtonText: {
    color: '#3B82F6',
    fontWeight: '800',
    fontSize: 16,
  },
  analysisOfferButtonTextSecondary: {
    color: '#0F131A',
    fontWeight: '800',
    fontSize: 16,
  },

  // Reminder Popup Styles - Colorful
  reminderPopup: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  reminderPopupContent: {
    backgroundColor: 'linear-gradient(135deg, #A5B4FC 0%, #C4B5FD 100%)',
    borderRadius: 24,
    padding: 24,
    margin: 20,
    maxHeight: '80%',
    width: '90%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  reminderPopupTitle: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
    color: '#0F131A',
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  reminderPopupSubtitle: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '500',
  },
  reminderSuggestionsList: {
    maxHeight: 300,
    marginBottom: 20,
  },
  reminderSuggestionItem: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    borderLeftWidth: 6,
    borderLeftColor: '#3B82F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  reminderSuggestionContent: {
    flex: 1,
    marginRight: 16,
  },
  reminderSuggestionTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
    color: '#1E40AF',
  },
  reminderSuggestionDesc: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 8,
    lineHeight: 20,
    fontWeight: '500',
  },
  reminderSuggestionTime: {
    fontSize: 13,
    color: '#3B82F6',
    fontWeight: '700',
  },
  reminderAddButton: {
    backgroundColor: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  reminderAddButtonText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '800',
  },
  reminderPopupActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    gap: 12,
  },
  reminderPopupButton: {
    backgroundColor: 'rgba(255,255,255,0.9)',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderRadius: 16,
    flex: 1,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  reminderPopupButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.8)',
  },
  reminderPopupButtonText: {
    color: '#3B82F6',
    fontWeight: '800',
    fontSize: 16,
  },
  reminderPopupButtonTextSecondary: {
    color: '#0F131A',
    fontWeight: '800',
    fontSize: 16,
  },
  timeSelectionContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: 'rgba(59, 130, 246, 0.1)',
  },
  timeSelectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  timeInput: {
    backgroundColor: '#F8FAFC',
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 12,
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  timeInputText: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '600',
  },
  daysContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 12,
    gap: 6,
  },
  dayButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  dayButtonActive: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  dayButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  dayButtonTextActive: {
    color: '#FFFFFF',
  },
  frequencyText: {
    fontSize: 12,
    color: '#6B7280',
    fontStyle: 'italic',
    marginTop: 6,
    fontWeight: '600',
  },
});
